### ISSUE TITLE
DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'

### ISSUE THREAD

**Issue by DazzDev** [mertushka/haxball.js#17] opened 2023-02-12 17:08 UTC
I'm running a 24/7 room with haxball.js and once in a while I get this error when a player leaves the room.

```
DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'
0|index    | 2023-02-12T14:57:40:     at RTCDataChannel.send (/home/dznunleashed/SimpleHaxballFutsal/node_modules/@koush/wrtc/lib/index.js:49:8)
0|index    | 2023-02-12T14:57:40:     at Na.mb (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:981:17)
0|index    | 2023-02-12T14:57:40:     at Ja.mb (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:1846:17)
0|index    | 2023-02-12T14:57:40:     at Fa.ad (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:1727:21)
0|index    | 2023-02-12T14:57:40:     at Fa.zh (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:1838:44)
0|index    | 2023-02-12T14:57:40:     at Fa.wh (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:1793:22)
0|index    | 2023-02-12T14:57:40:     at a.$e (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:1685:15)
0|index    | 2023-02-12T14:57:40:     at Na.e.onmessage (/home/dznunleashed/SimpleHaxballFutsal/node_modules/haxball.js/src/index.js:392:66)
0|index    | 2023-02-12T14:57:40:     at /home/dznunleashed/SimpleHaxballFutsal/node_modules/@koush/wrtc/lib/eventtarget.js:37:18
0|index    | 2023-02-12T14:57:40:     at Set.forEach (<anonymous>)
```
I've also encountered this error without the last line (`at Set.forEach (<anonymous>)`).
I want to say it has had an impact on the server once, introducing some bugs related to moving players to teams, but I'm not 100% sure as I can't recreate the error message.

**Comment by mertushka** [comment] 2023-02-14 15:28
I don't think it's a problem with haxball.js as I implemented Haxball Headless one-on-one, it's probably a bug (null player id etc.) with your handling player leave function. Please, review your code and debug with breakpoints.

Let me know if your issue is still relevant.

**Comment by DazzDev** [comment] 2023-02-18 00:43
I tried and tried and can't recreate the error. Wouldn't the stack trace mention one of my .ts files if the issue was related to my `onPlayerLeave` function?

**Comment by mertushka** [comment] 2023-05-19 12:06
@basro Any idea on this?

**Comment by mertushka** [comment] 2023-05-19 12:36
> I want to say it has had an impact on the server once, introducing some bugs related to moving players to teams, but I'm not 100% sure as I can't recreate the error message.

Do you think it has something to do with this bug?

**Comment by mertushka** [comment] 2023-08-03 22:09
I'm closing this issue because it seems not a harmful bug also we can't reproduce it in any way.

**Closed by mertushka** 2023-08-03 22:09 UTC
Labels: bug

**Comment by jerryoldson** [comment] 2023-09-29 00:36
I'm having this exact same issue. It closes my room and have to open it every time it happens.

```
DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (/home/facundocachuzumba/node_modules/[4m@koush[24m/wrtc/lib/index.js:49:8)
    at Na.mb (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:981:17)
    at Ja.mb (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:1846:17)
    at Fa.ad (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:1727:21)
    at Fa.zh (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:1838:44)
    at Fa.wh (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:1793:22)
    at a.$e (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:1685:15)
    at Na.e.onmessage (/home/facundocachuzumba/node_modules/[4mhaxball.js[24m/src/index.js:392:66)
    at /home/facundocachuzumba/node_modules/[4m@koush[24m/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)

```
Don't know how to reproduce it.
